config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  authenticate :user, -> (u) { u.has_role? :admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'home#index'
  scope module: :users do
    get 'user/color/:color', to: 'users#color'
  end
  scope ':locale' do
    get '/home/search', to: 'home#search'

    resources :songs do
      get :like, on: :member
      get :search, on: :collection
      get :not_active, on: :collection
      get :do_active, on: :member
    end

    scope module: :admin do
      resources :performers

      get 'users/all/', to: 'users#index'
      get 'user/:id/do_admin', to: 'users#do_admin'
      get 'user/:id/do_user', to: 'users#do_user'
    end
  end
end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id                  :integer          not null, primary key
#  title               :string
#  body                :text
#  count_views         :integer          default(0)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  active              :integer          default(0)
#  likes_count         :integer          default(0)
#  slug                :string
#  user_id             :integer
#  avatar_file_name    :string
#  avatar_content_type :string
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  performer_id        :integer
#

class Song < ApplicationRecord
  extend FriendlyId
  include Paperclip::Glue

  has_many :likes, dependent: :destroy
  has_many :song, through: :likes, inverse_of: :songs
  belongs_to :user
  belongs_to :performer

  has_attached_file :avatar, styles: { thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :avatar, content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']

  validates :title, presence: true
  validates :body, presence: true

  friendly_id :title, use: [:slugged]

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :russian).to_s
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  load_and_authorize_resource find_by: :slug

  def index
    #search = Song.search(include: [:performer, :likes]) do
    #  with :active, 1
    #  order_by :created_at, :desc
    #  paginate page: params[:page], per_page: 15
    #end
    @songs = Song.all
  end

  def show
    @song.update_attributes(count_views: @song.count_views + 1)
  end

  def new; end

  def create
    @song = Song.new(song_params)
    if verify_recaptcha(model: @song) && @song.save
      UserMailer.send_add_song(@song.user, @song).deliver_now!
      redirect_to @song, success: t('controllers.songs.success_create')
    else
      flash[:error] = @song.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def update
    if verify_recaptcha(model: @song) && @song.update(song_params)
      redirect_to @song, success: t('controllers.songs.success_update')
    else
      flash[:error] = @song.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @song.destroy
      redirect_to songs_path, success: t('controllers.songs.success_delete')
    else
      flash[:error] = @song.errors.full_messages.to_sentence
    end
  end

  def like
    if Like.find_by(user_id: current_user.id, song_id: @song.id)
      redirect_to song_path(@song), error: t('controllers.songs.like_error')
    else
      Like.create(user_id: current_user.id, song_id: @song.id)
      redirect_to song_path(@song), success: t('controllers.songs.like_success')
    end
  end

  def search
    search = Song.search(include: :performer) do
      fulltext params[:title].downcase
      with :active, 1
      order_by :created_at, :desc
      paginate page: params[:page], per_page: 30
    end
    @songs = search.results
  end

  def not_active
    search = Song.search(include: :performer) do
      with :active, 0
      order_by :created_at, :desc
      paginate page: params[:page], per_page: 30
    end
    @songs = search.results
  end

  def do_active
    @song.update(active: 1)
    UserMailer.send_add_song_active(@song.user, @song).deliver_now!
    redirect_to not_active_songs_path, success: t('controllers.songs.active')
  end

  private

  def song_params
    params.require(:song).permit(:performer_id, :title, :body, :likes_count, :slug, :avatar).merge(user_id: current_user.id)
  end
end

app/views/songs/_index.html.slim
.row
  - @songs.each do |song|
    .col-lg-4.col-sm-4.col-xs-12.center.bottom
      .demo-card-event.mdl-card.mdl-shadow--2dp
        .mdl-card__title.mdl-card--expand style="background: url('#{song.avatar}'); background-position: center; background-repeat: no-repeat; background-size: cover;"
          .card-header-left
            .material-icons.mdl-badge.mdl-badge--overlap data-badge="#{song.likes.size}" 
              - if current_user && !song.likes.any? { |like| like.user_id === current_user.id }
                = link_to like_song_path(song)
                  = fa_icon('heart')
              - else
                .likes-user-songs
                  = fa_icon('heart')
            .material-icons.mdl-badge.mdl-badge--overlap data-badge="#{song.count_views}" 
              = fa_icon('eye')
        .mdl-card__actions.mdl-card--border
          = link_to song_path(song)
            .mdl-button.mdl-button--colore.mdl-js-button.mdl-js-ripple-effect
              = "#{song.performer.title} - #{song.title}"
.row
  .col-xs-12.text-align-center
    = paginate @songs

app/views/songs/edit.html.slim
= provide :site_title, t('views.pages.edit_song')
= provide :li_all_songs, 'active'
.row#card
  .col-lg-6.col-lg-offset-3.col-md-7.col-md-offset-2.col-sm-10.col-sm-offset-1.col-xs-12
    .demo-card-square.mdl-card.mdl-shadow--2dp id='song-cart'
      .mdl-card__title.mdl-card--expand
        = image_tag('music/4', class: 'devise-image-cart')
        h2.mdl-card__title-text
          = t('views.home.edit_song')
      .mdl-card__supporting-text
        = form_for @song, method: :put, html: { multipart: true } do |f|
          #form
            .file_input_div
              .file_input
                label.image_input_button.mdl-button.mdl-js-button.mdl-button--fab.mdl-button--mini-fab.mdl-js-ripple-effect.mdl-button--colored
                  i.material-icons file_upload
                  input.none#file_input_file type="file" name="song[avatar]"
              .mdl-textfield.mdl-js-textfield.textfield-demo#file_input_text_div
                input.file_input_text.mdl-textfield__input#file_input_text type="text" disabled="disabled" readonly="readonly" placeholder="#{t('views.global.form.avatar')}"
            .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
              = f.collection_select(:performer_id, Performer.all, :id, :title, {}, {class: 'dropdown'})

            .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
              = f.text_field :title, class: 'mdl-textfield__input', autofocus: true, required: true, minlength: 3
              = f.label t('views.song.title'), class: 'mdl-textfield__label'

            .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
              = f.text_area :body, class: 'mdl-textfield__input', rows: 10, cols: 45, required: true, minlength: 15
              = f.label t('views.song.body'), class: 'mdl-textfield__label'

            .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
              = recaptcha_tags
            br
            br
            = f.submit t('views.pages.edit_song'), id: 'button-submit', class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent'
            = spinner_css

app/views/songs/index.html.slim
= provide :site_title, t('views.home.all_songs')
= provide :li_all_songs, 'active'
= render 'index', locals: {songs: @songs}

app/views/songs/new.html.slim
= provide :site_title, t('views.home.add_song')
= provide :li_add_song, 'active'

.row.card
  .col-lg-5.col-lg-offset-4.col-md-5.col-md-offset-3.col-sm-10.col-xs-12
    /! Square card
    .demo-card-square.mdl-card.mdl-shadow--2dp id='song-card'
      .mdl-card__title.mdl-card--expand
        = image_tag('music/4', class: 'devise-image-card')
        h2.mdl-card__title-text
          = t('views.home.add_song')

      .mdl-card__supporting-text
        = form_for @song, html: { multipart: true } do |f|
          #form
            .file_input_div
              .file_input
                label.image_input_button.mdl-button.mdl-js-button.mdl-button--fab.mdl-button--mini-fab.mdl-js-ripple-effect.mdl-button--colored
                  i.material-icons file_upload
                  input.none#file_input_file type="file" name="song[avatar]"
              .mdl-textfield.mdl-js-textfield.textfield-demo#file_input_text_div
                input.file_input_text.mdl-textfield__input#file_input_text type="text" disabled="disabled" readonly="readonly" placeholder="#{t('views.global.form.avatar')}"

            .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
              = f.label t('views.song.performer'), class: 'mdl-textfield__label'
            .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
              = f.collection_select(:performer_id, Performer.all, :id, :title, {}, {class: 'dropdown'})

            .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
              = f.text_field :title, class: 'mdl-textfield__input', autofocus: true, required: true, minlength: 3
              = f.label t('views.song.title'), class: 'mdl-textfield__label'

            .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
              = f.text_area :body, class: 'mdl-textfield__input', rows: 10, cols: 45, required: true, minlength: 15
              = f.label t('views.song.body'), class: 'mdl-textfield__label'

            .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
              = recaptcha_tags
            br
            br
            = f.submit t('views.global.form.add'), id: 'button-submit', class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent'
            = spinner_css

app/views/songs/not_active.html.slim
= provide :site_title, t('views.pages.new_songs')
= provide :li_new_songs, 'active'
.row
  .col-lg-8.col-lg-offset-2.col-xs-12
    - @songs.each do |items|
      .songs-list-block
        span.mdl-chip.mdl-chip--contact
          span.mdl-chip__contact.mdl-color--teal.mdl-color-text--white
            = fa_icon('music')
          span.mdl-chip__text.song-chip-text
            .song-title-a
              = link_to song_path(items) do
                = "#{items.performer.title} - #{items.title}"

            .song-title-component
              span.mdl-chip__contact.mdl-color--teal-pink.mdl-color-text--white
                = link_to do_active_song_path(items) do
                  = fa_icon('check-square-o')

.row
  .col-xs-12.text-align-center
    = paginate @songs

app/views/songs/search.html.slim
= provide :site_title, t('views.home.search_results')
= provide :li_all_songs, 'active'
h2.mdl-card__title-text
  = t('views.home.search_results')
= render 'index', locals: { songs: @songs}

app/views/songs/show.html.slim
= provide :site_title, @song.title
= provide :li_all_songs, 'active'

.row.card
  p#add +
  p#subtract -
  .col-xs-12
    .demo-card-wide.mdl-card.mdl-shadow--2dp
      .mdl-card__title style="background: url(#{@song.avatar}) no-repeat; background-size: 100%;"
        .mdl-chip__text.song-chip-text.mdl-card__title-text
          .title-a
            = link_to performer_path(@song.performer)
              = @song.performer.title
            = " - #{@song.title}"
  
      .mdl-card__supporting-text
        .song-body
          pre
            = @song.body.html_safe
      .mdl-card__actions.mdl-card--border.space-between
        == social_share_button_tag(@song.title, desc: @song.body.to_s.strip.gsub!("'", "\""))

        p.song-who-add
          == t('views.song.thanks', parameter: @song.user.name)

      .mdl-card__menu
        - if current_user && current_user.has_role?(:admin)
          .song-title-component
            span.mdl-chip__contact.mdl-color--teal-pink.mdl-color-text--white
              = link_to edit_song_path(@song) do
                = fa_icon('edit')

            span.mdl-chip__contact.mdl-color--teal-pink.mdl-color-text--white
              = link_to song_path(@song), id: @song.id, method: :delete, data: { confirm: t('views.song.delete.confirm') } do
                = fa_icon('remove')

        - else
          .song-title-component
            span.mdl-chip__contact.mdl-color--teal-pink.mdl-color-text--white
              = link_to like_song_path(@song) do
                = fa_icon('heart')

            span.mdl-chip__text.margin-right-teen
              = @song.likes.size

            span.mdl-chip__contact.mdl-color--teal.mdl-color-text--white
              = fa_icon('eye')
            span.mdl-chip__text
              = @song.count_views