config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  authenticate :user, -> (u) { u.has_role? :admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'home#index'
  scope module: :users do
    get 'user/color/:color', to: 'users#color'
  end
  scope ':locale' do
    get '/home/search', to: 'home#search'

    resources :songs do
      get :like, on: :member
      get :search, on: :collection
      get :not_active, on: :collection
      get :do_active, on: :member
    end

    scope module: :admin do
      resources :performers

      get 'users/all/', to: 'users#index'
      get 'user/:id/do_admin', to: 'users#do_admin'
      get 'user/:id/do_user', to: 'users#do_user'
    end
  end
end

app/models/performer.rb
# == Schema Information
#
# Table name: performers
#
#  id                  :integer          not null, primary key
#  title               :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  slug                :string
#  avatar_file_name    :string
#  avatar_content_type :string
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#

class Performer < ApplicationRecord
  DEFAULT_URL = '/images/:style/missing.png'.freeze
  PATH = ':rails_root/public/images/:class/:attachment/:id/:style/:filename'.freeze
  URL = '/images/:class/:attachment/:id/:style/:filename'.freeze
  extend FriendlyId
  include Paperclip::Glue

  has_many :songs, dependent: :destroy

  has_attached_file :avatar, styles: { thumb: '100x100>' }, default_url: DEFAULT_URL, path: PATH, url: URL
  validates_attachment_content_type :avatar, content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']

  validates :title, presence: true

  friendly_id :title, use: [:slugged]

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :russian).to_s
  end
end

app/controllers/admin/performers_controller.rb
module Admin
  class PerformersController < ApplicationController
    load_and_authorize_resource find_by: :slug

    def index
      #search = Performer.search do
      #  order_by :created_at, :desc
      #  paginate page: params[:page], per_page: 30
      #end
      @performers = Performer.all
    end

    def show; end

    def new; end

    def create
      @performer = Performer.new(performer_params)
      if @performer.save
        redirect_to @performer, success: t('controllers.performers.success_create')
      else
        flash[:error] = @performer.errors.full_messages.to_sentence
        render :new
      end
    end

    def edit; end

    def update
      if @performer.update(performer_params)
        redirect_to @performer, success: t('controllers.performers.success_update')
      else
        flash[:error] = @performer.errors.full_messages.to_sentence
        render :edit
      end
    end

    def destroy
      if @performer.destroy
        redirect_to performers_path, success: t('controllers.performers.success_delete')
      else
        flash[:error] = @performer.errors.full_messages.to_sentence
      end
    end

    private

    def performer_params
      params.require(:performer).permit(:title, :avatar)
    end
  end
end

app/views/admin/performers/edit.html.slim
= provide :site_title, t('views.pages.edit_performer')
.row
  .col-lg-5.col-lg-offset-4.col-md-5.col-md-offset-3.col-sm-10.col-xs-12
    /! Square card
    .demo-card-square.mdl-card.mdl-shadow--2dp id='performer-cart'
      .mdl-card__title.mdl-card--expand
        = image_tag('music/4', class: 'devise-image-cart')
        h2.mdl-card__title-text
          = t('views.pages.edit_performer')
      .mdl-card__supporting-text
        = form_for @performer, method: :put do |f|
          #form
            .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
              = f.text_field :title, class: 'mdl-textfield__input', autofocus: true, required: true, minlength: 3
              = f.label t('views.performer.form.title'), class: 'mdl-textfield__label'
            br
            br
            = f.submit t('views.global.form.edit'), id: 'button-submit', class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent'
            = spinner_css

app/views/admin/performers/index.html.slim
= provide :site_title, t('views.pages.performers')
= provide :li_all_performers, 'active'
.row
  .col-xs-12.text-align-center
    p = t('views.pages.performers')
  .col-lg-8.col-lg-offset-2.col-xs-12
    - @performers.each do |item|
      .performers-list-block
        span.mdl-chip.mdl-chip--contact
          span.mdl-chip__contact.mdl-color--teal.mdl-color-text--white
            = fa_icon('user')
          span.mdl-chip__text.performer-chip-text
            .performer-title-a
              = link_to performer_path(item)
                = "#{item.title}"
          .performer-title-component
            span.mdl-chip__contact.mdl-color--teal-pink.mdl-color-text--white
              = link_to edit_performer_path(item) do
                = fa_icon('edit')

            span.mdl-chip__contact.mdl-color--teal-pink.mdl-color-text--white
              = link_to performer_path(item), method: :delete, data: {confirm: t('views.global.page.delete_confirm'), id: item.id} do
                = fa_icon('remove')

.row
  .col-xs-12.text-align-center
    = paginate @performers

app/views/admin/performers/new.html.slim
= provide :site_title, t('views.pages.new_performers')
= provide :li_add_performer, 'active'
.row
  .col-lg-5.col-lg-offset-4.col-md-5.col-md-offset-3.col-sm-10.col-xs-12
    /! Square card
    .demo-card-square.mdl-card.mdl-shadow--2dp id='performer-cart'
      .mdl-card__title.mdl-card--expand
        = image_tag('music/4', class: 'devise-image-cart')
        h2.mdl-card__title-text
          = t('views.pages.new_performers')

      .mdl-card__supporting-text
        = form_for @performer, html: { multipart: true } do |f|
          #form
            .file_input_div
              .file_input
                label.image_input_button.mdl-button.mdl-js-button.mdl-button--fab.mdl-button--mini-fab.mdl-js-ripple-effect.mdl-button--colored
                  i.material-icons file_upload
                  input.none#file_input_file type="file" name="performer[avatar]"
              .mdl-textfield.mdl-js-textfield.textfield-demo#file_input_text_div
                input.file_input_text.mdl-textfield__input#file_input_text type="text" disabled="disabled" readonly="readonly" placeholder="#{t('views.global.form.avatar')}"

            .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
              = f.text_field :title, class: 'mdl-textfield__input', autofocus: true, required: true, minlength: 3
              = f.label t('views.performer.form.title'), class: 'mdl-textfield__label'

            br
            br
            = f.submit t('views.global.form.add'), id: 'button-submit', class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent'
            = spinner_css

app/views/admin/performers/show.html.slim
= provide :site_title, @performer.title
= provide :li_all_performers, 'active'
.row
  .col-lg-8.col-lg-offset-2.col-xs-12
    .performers-list-block
      span.mdl-chip.mdl-chip--contact
        span.mdl-chip__contact.mdl-color--teal.mdl-color-text--white
          = fa_icon('music')
        span.mdl-chip__text.performer-chip-text
          .performer-title-a
            = @performer.title

          - if current_user && current_user.has_role?(:admin)
            .performer-title-component
              span.mdl-chip__contact.mdl-color--teal-pink.mdl-color-text--white
                = link_to edit_performer_path(@performer) do
                  = fa_icon('edit')

              span.mdl-chip__contact.mdl-color--teal-pink.mdl-color-text--white
                = link_to performer_path(@performer), id: @performer.id, method: :delete, data: { confirm: t('views.global.page.delete_confirm') } do
                  = fa_icon('remove')

.row
  .col-xs-12
    .center.performer-songs-title
      = t('views.home.songs')

.row
  .col-lg-8.col-lg-offset-2.col-xs-12
    - @performer.songs.each do |items|
      .songs-list-block
        span.mdl-chip.mdl-chip--contact
          span.mdl-chip__contact.mdl-color--teal.mdl-color-text--white
            = fa_icon('music')
          span.mdl-chip__text.song-chip-text
            .song-title-a
              = link_to song_path(items)
                = "#{items.performer.title} - #{items.title}"

            .song-title-component
              span.mdl-chip__contact.mdl-color--teal-pink.mdl-color-text--white
                - unless items.likes.size != 0
                  = link_to like_song_path(items)
                    = fa_icon('heart')
                - else
                  .likes-user-songs
                    = fa_icon('heart')

              span.mdl-chip__text.margin-right-teen id="song-id-#{items.id}"
                = items.likes.size

              span.mdl-chip__contact.mdl-color--teal.mdl-color-text--white
                = fa_icon('eye')
              span.mdl-chip__text
                = items.count_views