config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  authenticate :user, -> (u) { u.has_role? :admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'home#index'
  scope module: :users do
    get 'user/color/:color', to: 'users#color'
  end
  scope ':locale' do
    get '/home/search', to: 'home#search'

    resources :songs do
      get :like, on: :member
      get :search, on: :collection
      get :not_active, on: :collection
      get :do_active, on: :member
    end

    scope module: :admin do
      resources :performers

      get 'users/all/', to: 'users#index'
      get 'user/:id/do_admin', to: 'users#do_admin'
      get 'user/:id/do_user', to: 'users#do_user'
    end
  end
end

app/views/layouts/_alert.html.slim
.header-alert
  - flash.each do |name, msg|
    = content_tag :div, class: "alert alert-#{ name == 'error' ? 'danger' : 'success' } alert-dismissable", role: 'alert' do
      button type="button" class="close" data-dismiss="alert" aria-hidden="true"
        |
          x
      = msg

app/views/layouts/_header.html.slim
= render 'layouts/alert'
.header-nav
  button#demo-menu-lower-right class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored header-nav-button"
    = fa_icon('ellipsis-v')

  ul.mdl-menu.mdl-menu--bottom-right.mdl-js-menu.mdl-js-ripple-effect for="demo-menu-lower-right"
    li class="#{yield :li_home}"
      = link_to root_path, class: 'mdl-menu__item' do
        = fa_icon 'home'
        '
        = t('views.pages.index')
    li class="#{yield :li_all_songs}"
      = link_to songs_path, class: 'mdl-menu__item' do
        = fa_icon 'music'
        '
        = t('views.home.all_songs')
    li class="mdl-menu__item--full-bleed-divider #{yield :li_add_song}"
      = link_to new_song_path, class: 'mdl-menu__item' do
        = fa_icon 'plus'
        '
        = t('views.home.add_song')

    - if user_signed_in?
      - if current_user.has_role? :admin
        li class="#{yield :li_add_performer}"
          = link_to new_performer_path, class: 'mdl-menu__item' do
            = fa_icon 'plus'
            '
            = t('views.pages.new_performers')
        li class="#{yield :li_all_performers}"
          = link_to performers_path, class: 'mdl-menu__item' do
            = fa_icon 'users'
            '
            = t('views.pages.performers')
        li class="#{yield :li_new_songs}"
          = link_to not_active_songs_path, class: 'mdl-menu__item' do
            = fa_icon 'music'
            '
            = t('views.pages.new_songs')

        li class="#{yield :li_all_users}"
          = link_to users_all_path, class: 'mdl-menu__item' do
            = fa_icon 'users'
            '
            = t('views.pages.users')

        li class="mdl-menu__item--full-bleed-divider"
          = link_to '/sidekiq', class: 'mdl-menu__item' do
            = fa_icon 'area-chart'
            '
            = t('views.pages.processes')

      li class="#{yield :li_edit_user}"
        = link_to edit_user_registration_path, class: 'mdl-menu__item' do
          = fa_icon 'pencil-square-o'
          '
          = t('views.pages.edit_profile')

      li class="mdl-menu__item--full-bleed-divider #{yield :li_sign_in}"
        = link_to destroy_user_session_path, method: :delete, class: 'mdl-menu__item' do
          = fa_icon 'sign-out'
          '
          = t('views.pages.sign_out')

    - else
      li class="#{yield :li_sign_in}"
        = link_to new_user_session_path, class: 'mdl-menu__item' do
          = fa_icon 'sign-in'
          '
          = t('views.pages.sign_in')

      li class="mdl-menu__item--full-bleed-divider #{yield :li_sign_up}"
        = link_to new_user_registration_path, class: 'mdl-menu__item' do
          = fa_icon 'registered'
          '
          = t('views.pages.registration')

    li.mdl-menu__item.locale
      = link_to_unless_current t('views.pages.ukrain'), locale: :uk do
        = fa_icon 'flag'
        '
        = t('views.pages.ukrain')

    li.mdl-menu__item.locale
      = link_to_unless_current t('views.pages.russian'), locale: :ru do
        = fa_icon 'flag'
        '
        = t('views.pages.russian')

    li.mdl-menu__item.locale
      = link_to_unless_current t('views.pages.english'), locale: :en do
        = fa_icon 'flag'
        '
        = t('views.pages.english')

app/views/layouts/application.html.slim
doctype html
html
head
  title
    = "#{yield(:site_title)} | Prochord"
  = csrf_meta_tags

  = stylesheet_link_tag 'application', media: 'all'
  = javascript_include_tag 'application'
  meta name="viewport" content="width=device-width, initial-scale=1"

body
.header-alert-block
= render 'layouts/header'
.container.body
  = yield